import {test} from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';
import {copy,SaveModel} from '../model.js';import {equipmentStats,fitReasons,installModule,replaceModule,mountId,slotModules} from '../equipment.js';
const data=JSON.parse(readFileSync(new URL('../equipment.json',import.meta.url))),catalog=JSON.parse(readFileSync(new URL('../catalog.json',import.meta.url)));
test('vision and mass match native game calculations for all 38 base loadouts',()=>{assert.equal(data.referenceStats.length,38);for(const ref of data.referenceStats){const v=catalog.vehicles.find(v=>v.name===ref.unit).template,s=equipmentStats(v,data);for(const key of ['range','fov','id'])assert.ok(Math.abs(s.best[key]-ref.vision[key])<.0001,ref.unit+' '+key);assert.ok(Math.abs(s.peripheralBase+s.peripheralAdded-ref.vision.peripheral)<.0001);for(const key of ['thermal','activeIR','passiveIR'])assert.equal(s[key],ref.vision[key],ref.unit+' '+key);assert.ok(Math.abs(s.massBase+s.massAdded-ref.mass)<.001,ref.unit+' mass');assert.deepEqual(s.armor.map(a=>a.base+a.builtIn),ref.armor);}});
test('compatibility matches native CheckAddModule for every module/slot in all base loadouts',()=>{let checked=0;for(const ref of data.referenceStats){const v=catalog.vehicles.find(v=>v.name===ref.unit).template;for(const slot of data.vehicles[ref.unit].slots)for(const name of Object.keys(data.modules)){assert.equal(fitReasons(v,slot,name,data).length===0,ref.fit[slot.id].includes(name),`${ref.unit} slot ${slot.id}: ${name}`);checked++;}}assert.ok(checked>10000);});
test('forced installation encodes extra mounts and preserves direction for incompatible fixed slots',()=>{const v=copy(catalog.vehicles.find(v=>v.name==='K-75BM').template),slot=data.vehicles[v.unitType].slots[0];assert.throws(()=>installModule(v,slot,'E80 Engine',data));installModule(v,slot,'E80 Engine',data,true);assert.deepEqual(v.moduleInstances.at(-1),{module:'E80 Engine',side:slot.side,originalSlotID:1000000+slot.id*10000,isPrimaryWeapon:slot.primary});assert.throws(()=>installModule(v,slot,'not a game module',data,true));});
test('armor is directional and types remain separate; optics update immediately',()=>{const v=copy(catalog.vehicles.find(v=>v.name==='K-75BM').template);v.moduleInstances=[];const slot=data.vehicles[v.unitType].slots.find(s=>s.side===1&&!s.hardpoint);installModule(v,slot,'Applique (Composite)',data);installModule(v,slot,'ERA (Advanced)',data,true);installModule(v,slot,'Thermal Imaging Optics',data,true);const s=equipmentStats(v,data);assert.deepEqual(s.armor[1].contributions.map(c=>[c.type,c.rating]),[['Applique',3],['AdvancedERA',6]]);assert.equal(s.armor[0].contributions.length,0);assert.equal(s.best.range,45);assert.equal(s.thermal,true);});
test('editing installed modules survives JSON roundtrip and undo without altering other vehicle fields',()=>{const v=copy(catalog.vehicles.find(v=>v.name==='S-92 Siegebreaker').template);v.id=42;v.unknown={preserve:true};const root={gameVersion:'0.6.3',gameData:{playerSquad:[v],motorPool:[],crewBarracks:[],crewAidbay:[],crewTraining:[],crewInstructor:[],moduleStorage:[]}};const model=new SaveModel(JSON.stringify(root));model.change(()=>installModule(model.data.playerSquad[0],data.vehicles[v.unitType].slots[0],'Thermal Imaging Optics',data,true));assert.deepEqual(new SaveModel(model.serialize()).data.playerSquad[0].unknown,v.unknown);model.undo();assert.deepEqual(model.root,root);});

test("extra mount IDs stay unique and regroup after reload",()=>{const v=copy(catalog.vehicles.find(v=>v.name==="K-75BM").template),slot=data.vehicles[v.unitType].slots[6];installModule(v,slot,"Thermal Imaging Optics",data,true);installModule(v,slot,"Thermal Imaging Optics",data,true);const a=v.moduleInstances.at(-2),b=v.moduleInstances.at(-1);assert.notEqual(a.originalSlotID,b.originalSlotID);assert.equal(mountId(a),slot.id);assert.equal(mountId(b),slot.id);assert.equal(slotModules(JSON.parse(JSON.stringify(v)),slot).length,3);});

test("replacing a module evaluates freed capacity and preserves position",()=>{const v=copy(catalog.vehicles.find(v=>v.name==="K-75BM").template),slot=data.vehicles[v.unitType].slots[6],old=slotModules(v,slot)[0],index=v.moduleInstances.indexOf(old);assert.equal(replaceModule(v,old,slot,"Applique (Composite)",data),"ERA (Simple)");assert.equal(v.moduleInstances[index].module,"Applique (Composite)");assert.equal(v.moduleInstances[index].originalSlotID,slot.id);});
test("failed replacement keeps the original module and the entire loadout",()=>{const v=copy(catalog.vehicles.find(v=>v.name==="K-75BM").template),slot=data.vehicles[v.unitType].slots[6],old=slotModules(v,slot)[0],before=copy(v);assert.throws(()=>replaceModule(v,old,slot,"Thermal Imaging Optics",data),/incompatible/);assert.deepEqual(v,before);replaceModule(v,old,slot,"Thermal Imaging Optics",data,true);assert.equal(slotModules(v,slot).length,1);assert.equal(mountId(slotModules(v,slot)[0]),slot.id);});
